version: "3.9"
services:
  db:
    image: "mysql:8.0.27"
    ports:
      - "3306:3306"
    volumes:
      - "./mysql-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: YasMys@1
    networks:
      - backend
  web:
    depends_on:
      - db
    build: .
    ports:
      - "8000:5000"
    volumes:
      - ".:/url-shortener-plus"
    environment:
      FLASK_ENV: development
    networks:
      - backend
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - backend
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_worker.celery worker --pool=solo --loglevel=info
    volumes:
      - ".:/url-shortener-plus"
    depends_on:
      - rabbitmq
    networks:
      - backend

networks:
  backend: